export const expenseCategories: string[] = [
  "Groceries",
      "Dining Out",
      "Transportation",
      "Fuel",
      "Public Transit",
      "Shopping",
      "Entertainment",
      "Travel",
      "Health & Fitness",
      "Subscriptions",
      "Gifts & Donations",
      "Education",
      "Personal Care",
      "Utilities",
      "Rent/Housing",
      "Insurance",
      "Miscellaneous",
];
